name: 'Secret Parser Binary'
author: 'James Webb'
description: 'Replaces GitHub Actions secrets referenced in files with their raw values'
inputs:
  filename:
    description: 'File where GitHub Actions Secrets references should be parsed and replaced'
    required: true
  secret-name:
    description: 'Name of secret to search for in the designated file'
    required: true
  secret-value:
    description: 'Value of secret to replace reference with in designated file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: ['${{ inputs.filename }}', '${{ inputs.secret-name }}', '${{ inputs.secret-value }}']
branding:
  icon: 'lock'
  color: 'blue'
